# Performing Calculations Using Vectors and Matrixes

In [1]:
import numpy as np

In [2]:
 myShort = np.short(15)

In [3]:
myShort

15

In [4]:
myVect = np.array([1, 2, 3, 4])

In [5]:
myVect

array([1, 2, 3, 4])

In [7]:
myVect = np.arange(1, 10, 2)

In [8]:
myVect

array([1, 3, 5, 7, 9])

In [10]:
# Create a vector with a data type
myVect = np.array(np.int16([1, 2, 3, 4]))
myVect2 = np.array([1, 2, 3, 4], dtype='int16')

In [11]:
myVect2

array([1, 2, 3, 4], dtype=int16)

In [12]:
myVect

array([1, 2, 3, 4], dtype=int16)

In [13]:
myVect = np.ones(4, dtype=np.int16)

In [14]:
myVect

array([1, 1, 1, 1], dtype=int16)

In [15]:
myVect = np.zeros(4, dtype=np.int16)

In [16]:
myVect

array([0, 0, 0, 0], dtype=int16)

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

In [18]:
a == b

array([False,  True, False,  True])

In [19]:
a < b

array([ True, False,  True, False])

In [20]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

In [21]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [22]:
np.logical_and(a, b)

array([ True, False, False, False])

In [23]:
np.logical_not(a, b)

array([False,  True, False,  True])

In [24]:
np.logical_xor(a, b)

array([ True,  True,  True,  True])